# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: "3"
services:

  selenium-runner:
    build: .
    command: ["/bin/sh", "-c", "yarn && yarn test:selenium"]
    depends_on:
      - selenium-hub
      - chrome
      - firefox

  selenium-hub:
    image: selenium/hub:3.141.59-radium
    container_name: selenium-hub

  chrome:
    image: selenium/node-chrome:3.141.59-radium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  firefox:
    image: selenium/node-firefox:3.141.59-radium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444